@extends('layouts.app')

@section('content')
<div class="bg-bg py-16 sm:py-24">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div class="text-center">
            <h1 class="text-4xl font-extrabold tracking-tight text-charcoal sm:text-5xl">
                Speaker Directory
            </h1>
            <p class="mt-4 max-w-2xl text-xl text-gray-600 mx-auto">
                Discover the international experts, policymakers, and academics joining us at BODHI SAMBAD 2026.
            </p>
        </div>

        @php
            if ($speakers->isEmpty()) {
                $speakers = collect([
                    (object) ['id' => 'maya-shrestha', 'name' => 'Dr. Maya Shrestha', 'role' => 'Panel Chair', 'organization' => 'Professor of International Relations, Tribhuvan University', 'image_url' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=900&q=80', 'bio' => 'Dr. Shrestha’s research focuses on regional diplomacy, governance reform, and the economic impact of infrastructure initiatives across South Asia.'],
                    (object) ['id' => 'li-wei', 'name' => 'Mr. Li Wei', 'role' => 'Keynote Speaker', 'organization' => 'Senior Research Fellow, Asia Policy Institute', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Mr. Li brings deep insight into policy trends, strategic frameworks, and multilateral diplomacy shaping China’s engagement in the region.'],
                    (object) ['id' => 'ayesha-patel', 'name' => 'Dr. Ayesha Patel', 'role' => 'Panelist', 'organization' => 'Economist, Regional Development Council', 'image_url' => 'https://images.unsplash.com/photo-1525097487452-6278ff080c31?auto=format&fit=crop&w=900&q=80', 'bio' => 'Ayesha explores regional economic integration strategies, trade diplomacy challenges, and the future of cross-border infrastructure finance.'],
                    (object) ['id' => 'rajiv-thapa', 'name' => 'Mr. Rajiv Thapa', 'role' => 'Panelist', 'organization' => 'Senior Analyst, Global Affairs Forum', 'image_url' => 'https://images.unsplash.com/photo-1524503033411-c9566986fc8f?auto=format&fit=crop&w=900&q=80', 'bio' => 'Rajiv’s analysis focuses on strategic alliances, risk assessment, and policy coherence across South Asia in light of global power shifts.'],
                    (object) ['id' => 'nisha-gupta', 'name' => 'Dr. Nisha Gupta', 'role' => 'Speaker', 'organization' => 'Director, South Asia Economic Institute', 'image_url' => 'https://images.unsplash.com/photo-1524503145539-992f7ca0a644?auto=format&fit=crop&w=900&q=80', 'bio' => 'Dr. Gupta researches economic corridors, supply chain resilience, and the digital transformation of regional trade.'],
                    (object) ['id' => 'amar-khan', 'name' => 'Mr. Amar Khan', 'role' => 'Speaker', 'organization' => 'Senior Fellow, Himalayan Security Initiative', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Amar’s work examines border management, transboundary water security, and the implications of new infrastructure in the Himalayas.'],
                    (object) ['id' => 'lina-chen', 'name' => 'Dr. Lina Chen', 'role' => 'Speaker', 'organization' => 'Associate Professor, School of International Affairs', 'image_url' => 'https://images.unsplash.com/photo-1524504390861-1d3d7f5ceef1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Lina focuses on international law, treaty frameworks, and the role of regional institutions in mediating great power competition.'],
                    (object) ['id' => 'tarek-hassan', 'name' => 'Mr. Tarek Hassan', 'role' => 'Speaker', 'organization' => 'Research Director, Trade & Connectivity Lab', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Tarek studies emerging trade routes, customs modernization, and the economic implications of the Belt and Road Initiative.'],
                    (object) ['id' => 'anita-das', 'name' => 'Dr. Anita Das', 'role' => 'Speaker', 'organization' => 'Senior Policy Advisor, Regional Cooperation Forum', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Anita specialises in development policy, energy transition, and community-driven frameworks for sustainable infrastructure.'],
                    (object) ['id' => 'mohammed-raza', 'name' => 'Mr. Mohammed Raza', 'role' => 'Speaker', 'organization' => 'Director, Urban Resilience Centre', 'image_url' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Mohammed brings experience on urban planning, climate resilience, and inclusive infrastructure financing across South Asian cities.'],
                    (object) ['id' => 'sara-fernandes', 'name' => 'Dr. Sara Fernandes', 'role' => 'Speaker', 'organization' => 'Professor of Diplomacy, Global Studies Institute', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Sara’s work explores diplomatic innovation, track-two dialogues, and the changing norms of international engagement.'],
                    (object) ['id' => 'rajesh-patel', 'name' => 'Mr. Rajesh Patel', 'role' => 'Speaker', 'organization' => 'Energy Analyst, Sustainable Futures Initiative', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Rajesh analyzes energy transition strategies, cross-border electricity trade, and regional cooperation on renewable infrastructure.'],
                    (object) ['id' => 'meera-chandra', 'name' => 'Dr. Meera Chandra', 'role' => 'Speaker', 'organization' => 'Senior Fellow, Peace & Security Centre', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Meera specializes in confidence-building measures, conflict prevention, and the security implications of transnational infrastructure.'],
                    (object) ['id' => 'hamid-al-khalid', 'name' => 'Mr. Hamid Al-Khalid', 'role' => 'Speaker', 'organization' => 'Director of Strategy, Regional Trade Consortium', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Hamid focuses on regional trade policy, logistics efficiency, and private sector partnerships for connectivity initiatives.'],
                    (object) ['id' => 'yasmin-solanki', 'name' => 'Dr. Yasmin Solanki', 'role' => 'Speaker', 'organization' => 'Research Fellow, GeoEconomics Lab', 'image_url' => 'https://images.unsplash.com/photo-1524504390861-1d3d7f5ceef1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Yasmin explores the intersection of economics and geopolitics, particularly how infrastructure shapes regional power balances.'],
                    (object) ['id' => 'sandeep-kumar', 'name' => 'Mr. Sandeep Kumar', 'role' => 'Speaker', 'organization' => 'Head of Partnerships, Connectivity Fund', 'image_url' => 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Sandeep leads partnership development for infrastructure projects, focusing on inclusive financing and governance best practices.'],
                    (object) ['id' => 'jung-eun-kim', 'name' => 'Dr. Jung Eun Kim', 'role' => 'Speaker', 'organization' => 'Senior Researcher, Regional Climate Initiative', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Jung Eun researches climate resilience, cross-border water management, and sustainable development frameworks for South Asia.'],
                    (object) ['id' => 'amir-rahman', 'name' => 'Mr. Amir Rahman', 'role' => 'Speaker', 'organization' => 'Economic Advisor, Trade & Investment Council', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Amir evaluates investment trends, bilateral trade agreements, and economic corridor opportunities across the region.'],
                    (object) ['id' => 'tara-kapoor', 'name' => 'Dr. Tara Kapoor', 'role' => 'Speaker', 'organization' => 'Director, Digital Infrastructure Lab', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Tara focuses on digital connectivity, data governance, and the implications of cross-border digital infrastructure for economic development.'],
                    (object) ['id' => 'javed-ali', 'name' => 'Mr. Javed Ali', 'role' => 'Speaker', 'organization' => 'Senior Analyst, Strategic Studies Group', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Javed writes on military balance, infrastructure security, and the role of defense cooperation in regional stability.'],
                    (object) ['id' => 'sunita-prasad', 'name' => 'Dr. Sunita Prasad', 'role' => 'Speaker', 'organization' => 'Climate Policy Specialist, Sustainable South Asia', 'image_url' => 'https://images.unsplash.com/photo-1524504390861-1d3d7f5ceef1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Sunita works on climate adaptation, green infrastructure policy, and the social dimensions of climate-resilient development.'],
                    (object) ['id' => 'ocean-nguyen', 'name' => 'Ms. Ocean Nguyen', 'role' => 'Speaker', 'organization' => 'Innovation Lead, Cross-Border Tech Initiative', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Ocean explores innovation ecosystems, digital trade, and the role of technology hubs in regional cooperation.'],
                    (object) ['id' => 'mehran-hussain', 'name' => 'Mr. Mehran Hussain', 'role' => 'Speaker', 'organization' => 'Policy Director, Infrastructure Finance Network', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Mehran focuses on public-private partnerships, risk mitigation, and sustainable financing models for large-scale projects.'],
                    (object) ['id' => 'nazanin-saeed', 'name' => 'Dr. Nazanin Saeed', 'role' => 'Speaker', 'organization' => 'Senior Fellow, Regional Governance Forum', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Nazanin researches governance innovations, accountability mechanisms, and inclusive decision-making in infrastructure planning.'],
                    (object) ['id' => 'hassan-karim', 'name' => 'Mr. Hassan Karim', 'role' => 'Speaker', 'organization' => 'Director, Supply Chain Resilience Centre', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Hassan studies supply chain vulnerabilities, logistics modernization, and regional cooperation on critical trade corridors.'],
                    (object) ['id' => 'parvati-rao', 'name' => 'Dr. Parvati Rao', 'role' => 'Speaker', 'organization' => 'Research Lead, Social Impact Lab', 'image_url' => 'https://images.unsplash.com/photo-1524504390861-1d3d7f5ceef1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Parvati explores how infrastructure projects can foster community resilience, gender equity, and inclusive development.'],
                    (object) ['id' => 'liang-zhou', 'name' => 'Dr. Liang Zhou', 'role' => 'Speaker', 'organization' => 'Senior Analyst, Regional Security Centre', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Liang focuses on maritime security, coastal infrastructure, and the role of naval presence in regional stability.'],
                    (object) ['id' => 'neha-sharma', 'name' => 'Ms. Neha Sharma', 'role' => 'Speaker', 'organization' => 'Environmental Policy Expert, Green Development Network', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Neha works on biodiversity conservation, sustainable infrastructure, and the environmental impact assessment of cross-border projects.'],
                    (object) ['id' => 'aminah-alvi', 'name' => 'Ms. Aminah Alvi', 'role' => 'Speaker', 'organization' => 'Trade Policy Specialist, South Asia Trade Council', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Aminah examines customs reform, non-tariff barriers, and the role of regional trade agreements in facilitating connectivity.'],
                    (object) ['id' => 'kumar-rajan', 'name' => 'Mr. Kumar Rajan', 'role' => 'Speaker', 'organization' => 'Director, Rural Development Institute', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Kumar studies rural infrastructure, inclusive growth models, and the social benefits of improved regional linkages.'],
                    (object) ['id' => 'emma-wong', 'name' => 'Dr. Emma Wong', 'role' => 'Speaker', 'organization' => 'Urban Planning Specialist, Metropolitan Policy Group', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Emma focuses on integrated urban development, transit-oriented growth, and sustainable city-region partnerships.'],
                    (object) ['id' => 'nikhil-sharma', 'name' => 'Mr. Nikhil Sharma', 'role' => 'Speaker', 'organization' => 'Economist, Infrastructure Finance Hub', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Nikhil’s research covers project finance, risk mitigation, and investor engagement in regional infrastructure.'],
                    (object) ['id' => 'tamilia-rahman', 'name' => 'Ms. Tamilia Rahman', 'role' => 'Speaker', 'organization' => 'Humanitarian Affairs Specialist, Crisis Response Network', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Tamilia highlights the role transport corridors and logistics play in disaster response and humanitarian access.'],
                    (object) ['id' => 'arjun-mehta', 'name' => 'Mr. Arjun Mehta', 'role' => 'Speaker', 'organization' => 'Policy Specialist, Energy Transition Initiative', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Arjun focuses on cross-border energy grids, renewable project collaboration, and energy security policies.'],
                    (object) ['id' => 'laura-fernando', 'name' => 'Dr. Laura Fernando', 'role' => 'Speaker', 'organization' => 'Director, Maritime Affairs Institute', 'image_url' => 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=900&q=80', 'bio' => 'Laura researches maritime law, port development, and the economic impact of sea lanes on regional trade.'],
                    (object) ['id' => 'dinesh-kumar', 'name' => 'Mr. Dinesh Kumar', 'role' => 'Speaker', 'organization' => 'Senior Advisor, Border Infrastructure Group', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Dinesh specializes in border crossings, customs modernization, and the integration of smart infrastructure at checkpoints.'],
                    (object) ['id' => 'karen-lee', 'name' => 'Dr. Karen Lee', 'role' => 'Speaker', 'organization' => 'Research Lead, Innovation in Governance', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Karen explores how digital tools and data sharing platforms can improve transparency in regional infrastructure projects.'],
                    (object) ['id' => 'arvind-patel', 'name' => 'Mr. Arvind Patel', 'role' => 'Speaker', 'organization' => 'Director, Cross-Border Cooperation Forum', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Arvind works on institutional mechanisms for dialogue, joint planning, and dispute resolution in regional infrastructure.'],
                    (object) ['id' => 'sophia-williams', 'name' => 'Dr. Sophia Williams', 'role' => 'Speaker', 'organization' => 'Director, Regional Integration Institute', 'image_url' => 'https://images.unsplash.com/photo-1520975914552-027c1c7e01d3?auto=format&fit=crop&w=900&q=80', 'bio' => 'Sophia focuses on public policy coordination, multilateral planning, and shared infrastructure governance.'],
                    (object) ['id' => 'omar-ali', 'name' => 'Mr. Omar Ali', 'role' => 'Speaker', 'organization' => 'Senior Analyst, Connectivity Policy Lab', 'image_url' => 'https://images.unsplash.com/photo-1544725176-7c40e5a2c9f9?auto=format&fit=crop&w=900&q=80', 'bio' => 'Omar studies trade facilitation, border procedures, and the economic benefits of improved regional linkages.'],
                    (object) ['id' => 'alex-singh', 'name' => 'Ms. Alex Singh', 'role' => 'Speaker', 'organization' => 'Regional Strategy Analyst, Connectivity Minds', 'image_url' => 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80', 'bio' => 'Alex examines regional planning, infrastructure resilience, and collaborative policy design across South Asia.'],
                ]);
            }
        @endphp

        <div class="mt-16 grid gap-12 sm:grid-cols-2 lg:grid-cols-3">
            @foreach($speakers as $speaker)
            <div data-speaker-id="{{ $speaker->id }}" role="button" tabindex="0" class="speaker-card bg-white rounded-3xl shadow-xl overflow-hidden hover:-translate-y-2 transition duration-500 border border-gray-100 flex flex-col cursor-pointer focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2 focus:ring-offset-white">
                <div class="h-80 overflow-hidden relative group border-b-4 border-accent">
                    <img class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" src="{{ $speaker->image_url }}" alt="{{ $speaker->name }}" />
                    <div class="absolute bottom-4 left-4 bg-white/90 backdrop-blur-sm px-4 py-1 rounded-full text-xs font-bold text-charcoal shadow-sm uppercase tracking-wider">
                        {{ $speaker->role }}
                    </div>
                </div>
                <div class="p-8 flex-grow flex flex-col justify-center text-center">
                    <h3 class="text-2xl font-bold text-charcoal">{{ $speaker->name }}</h3>
                    <div class="h-1 w-10 bg-accent rounded-full mx-auto my-4"></div>
                    <p class="text-gray-600 font-medium leading-relaxed">{{ $speaker->organization }}</p>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

{{-- Include the modal component --}}
@include('components.speaker-modal')